### ISSUE TITLE
bool vs darling::Flag for certain options

### ISSUE THREAD

**Issue by TedDriggs** [chipsenkbeil/entity-rs#28]
Some options such as `no_builder` are currently declared as type `bool`, which means `no_builder = false` is technically valid. Mechanically, that means "yes, I do want a builder," but it's not clear that a double-negative is required in this case.

[`darling::util::Flag`](https://docs.rs/darling/0.12.0/darling/util/struct.Flag.html) provides a `bool`-like interface without allowing boolean literals in the attribute; instead only the word form is allowed. Does it make sense to switch over and tighten the API definition?

**Comment by chipsenkbeil** [comment]
Yes, I think that makes more sense to use. I had missed the util module of darling back when I was first figuring out how to use it.

**Comment by chipsenkbeil** [comment]
I'll be removing `no_builder` and similar attrs in favor of #24 where you need to explicitly derive the builder via `EntBuilder` instead.

This would still be relevant for `#[ent(field(indexed, mutable))]`, though.
