### ISSUE TITLE
Validate that only one of [id, database, created, last_updated] is present on a single field

### ISSUE THREAD

**Issue by TedDriggs** [chipsenkbeil/entity-rs#30]
I don't think this is supposed to be valid:

```rust
#[derive(Debug, Ent)]
struct What {
    #[ent(id, database, created, last_updated)]
    how: String,
}
```

Experience-wise, the most consistent and precise behavior feels like it would be, "if a field declares multiple ent-field words, they all get errors." That avoids needing to worry about order of appearance in the derive input and avoids leaking to the user the order in which the checks take place in the proc-macro.

This shouldn't otherwise block parsing or validation, so the shape of `internal::EntField` wouldn't change, but it's probably useful to have it expose a method for checking this condition to avoid many-way if-statements spreading far throughout the codebase.

One open question: Should a field that claims to be both `id` and `database` count in the "__ already declared elsewhere" check? If so, then this new validation goes inside the per-field loop before the big if/else tree. If not, then maybe the best approach is to add `fn known_field(&self) -> Option<darling::Result<KnownField>>` to `internal::EntField` and then branching off that in the per-field loop?

**Comment by chipsenkbeil** [comment]
Yes, you're right, that should be an error! Given I originally was working with the "fail after the first error" model with `syn::Error`, I'm not sure what the best approach here would be. My gut says that if you have one field marked as `id` and `database` and another marked as `id`, you would get the error about "id already declared elsewhere" alongside the "multiple ent-field words defined".

**Comment by TedDriggs** [comment]
That sounds pretty good (and is actually the easiest one to implement, too).
